### ISSUE TITLE
Gray screen after install 

### ISSUE THREAD

**Issue by venterum** [koeqaife/hyprland-material-you#143]
Just ran the script and got a gray screen with a cursor when logged into hyprland. No shortcuts work, maybe I did something wrong? Same happened after reinstall. I am new to hyprland so I hope someone can help me.

**Comment by koeqaife** [comment]
I guess hypr config didn't work. Dotfiles are in ~/dotfiles????

**Comment by venterum** [comment]
Heah, I guess so, I did another reinstall and got it 
![IMG_20241224_021238947.jpg](https://github.com/user-attachments/assets/4401254a-ebd9-44da-bc98-c6b221bf2eae)

The screen stays the same but I got some errors

**Comment by koeqaife** [comment]
source= is not working. Try `rm ~/.config/hypr && ln -s ~/dotfiles/hypr ~/.config/hypr`. Make sure that dotfiles are in ~/dotfiles/ and not in ~/dotfiles/dotfiles

**Comment by venterum** [comment]
Okey, I'll try it a bit later and then let you know, thanks

**Comment by koeqaife** [comment]
and also run `python ~/dotfiles/hypr/scripts/wallpaper.py -R`

**Comment by venterum** [comment]
> and also run `python ~/dotfiles/hypr/scripts/wallpaper.py -R`

Got this error

```
python ~/dotfiles/hypr/scripts/wallpaper.py -R
Traceback (most recent call last):
  File "/home/venterum/dotfiles/hypr/scripts/wallpaper.py", line 75, in <module>
    spec.loader.exec_module(GENERATOR)   # type: ignore
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/venterum/dotfiles/material-colors/generate.py", line 7, in <module>
    from materialyoucolor.quantize import QuantizeCelebi  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'materialyoucolor'
```

**Comment by koeqaife** [comment]
run `~/dotfiles/install.sh packages` it'll install python packages again

**Comment by venterum** [comment]
> run `~/dotfiles/install.sh packages` it'll install python packages again 

Update, nothing helped, still same errors :(

**Comment by koeqaife** [comment]
Okay, try `yay -S python-materialyoucolor-git`

**Comment by koeqaife** [comment]
So?

**Comment by venterum** [comment]
> So?

Sry for this silence, so no, it didn't help. 

I also tried using the script on a clean arch installation and I have the same problems, which I don't really want to deal with. Apparently there are some dependencies that are not installed during the script and they cause that nothing works properly. As far as I know, you have a Discord and I would be very grateful if we could communicate there, especially as I understand you understand Russian

**Comment by koeqaife** [comment]
Okay, join the discord server I'll help you there. And yes I speak russian

**Comment by koeqaife** [comment]
So?

**Comment by SakibShahariar** [comment]
for me it's black screen and cursor in the middle, tried 3 times but still stuck, and i am in EndeavourOS.

**Comment by koeqaife** [comment]
Any issues related to v1 is gonna be closed. Cuz I'm writing v2 update that won't use ags or any other libraries (I'll use pure gtk4)
